# Numpy Task

### Instructions:
- Answer the following questions using NumPy only.
- Do not use Python loops unless explicitly stated.

## Part 1: Creating Arrays (3 Questions)


####  1) Create a NumPy array that contains all even numbers between 10 and 50 (inclusive).


In [7]:
import numpy as np
print(np.arange(10 , 51 , 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]





#### 2) Create an array of shape (3, 4) filled with ones, then change all values in the last column to 0.



In [16]:
import numpy as np
arr = np.ones((3,4))
arr[:,-1].fill(0)
print(arr)

[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]





#### 3) Create a NumPy array of 5 equally spaced numbers between -1 and 1.

In [17]:
import numpy as np
print(np.linspace(-1,1,5))

[-1.  -0.5  0.   0.5  1. ]


## Part 2: Array Properties (3 Questions)

#### 1) Create array and then 
- Find its shape

- Number of elements

- Data type

In [19]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 3)
9
int64


#### 2) Create a random array of size 10 and find:
- minimum value

- maximum value

- standard deviation

In [27]:
import numpy as np
arr = np.linspace(0,10,2)
print(arr.min())
print(arr.max())
print(arr.std())

0.0
10.0
5.0


#### 3) What is the difference between arr.size and arr.shape?

- Explain using an example.

In [ ]:
# arr.size return the number of elements in the array 
# arr.shape return the dimensions of the array.

## Part 3: Mathematical Operations & ufuncs (3 Questions)

#### 1) Create a new array that contains the square of each element without using loops.

In [36]:
# Given 

arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)
print(arr ** 2)


[ 2  4  6  8 10]
[ 1  4  9 16 25]


#### 2) Compute the mean and sum of all values in a 3×3 random matrix.

In [32]:
arr = np.array([1, 2, 3, 4, 5 , 6 , 7 , 8 , 9])
arr = arr.reshape(3,3)
print(np.mean(arr))

5.0


#### 3) Compute the mean and sum of all values in a 3×3 random matrix.

In [33]:
arr = np.array([1, 2, 3, 4, 5 , 6 , 7 , 8 , 9])
arr = arr.reshape(3,3)
print(np.mean(arr))

5.0


## Part 4: Indexing, Slicing & Boolean Indexing (4 Questions)

#### 1) Extract the middle four elements using slicing.

In [34]:
# Given 
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5])

[20 30 40 50]


#### 2) From the same array, extract all values greater than 25.

In [35]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr > 25)

[False False  True  True  True  True]


#### 3) Modify the array so that all values less than 30 become 0.

In [38]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.where(arr < 30, 0, arr))

[ 0  0 30 40 50 60]


#### 4) When would slicing be better than Boolean indexing?
Give one example.

In [39]:
# slicing is a useful if i know the index and i want to access a specific range of elements in the array.
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5])

[20 30 40 50]


## Part 5: Random Numbers & Performance (3 Questions)

#### 1) Generate a reproducible array of 15 random integers between 1 and 100.

In [48]:
import numpy as np
print(np.random.randint(1, 101, size=15))

[12 90 28 46 80 59 75 74 84 56 57 58 80 90 36]


#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization 

``to add 10 to each element.``

**Which one is faster and why?**

In [50]:
arr_for_loop = [1,2,3,4,5,6,7,8,9,10]
for i in arr_for_loop:
    print(i+10)

11
12
13
14
15
16
17
18
19
20


In [52]:
import numpy as np
arr_with_vectorization = np.arange(1,11)
print(arr_with_vectorization + 10)

[11 12 13 14 15 16 17 18 19 20]


#

### i think NumPy vectorization is father because the for loop to add a value is o(n)

#### 4) Why is `np.random.seed()` important in data science experiments?

## Part 6: Linear Algebra & Matrix Operations (2 Questions)

#### 1) Compute the determinant and inverse of a square matrix of your choice.

#### 2) What is the difference between:

- element-wise multiplication

- matrix multiplication
in NumPy?

## Bonus (Optional – Mindset Question)

#### How does NumPy help a Data Analyst think in a vectorized and mathematical way instead of a procedural one?